permalink: pretty

collections:
  rels:
    output: true
    permalinks: /rel/:path

defaults:
  -
    scope:
      path: ""
      type: rels
    values:
      layout: rel

sass:
  sass_dir: css
  style: :compressed
